baseURL: "https://stefansblog.org"
title: stefansblog
paginate: 5
theme: [hugo-WonderMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: true
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "$(whoami)","Blog",]

minify:
  disableXML: true

languages:
  en:
    languageName: "German"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Blog
          url: https://stefansblog.org/posts
          weight: 5
       


  

    params:
      languageAltTitle: german
      social: true
      profileMode:
        enabled: false
        title: Stefansblog
        imageUrl: ""
        imageTitle: ProfileMode image
        subtitle: ""
        buttons:
          - name: Blog
            url: posts
          - name: Profile Mode
            url: https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode

 

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "placeholder"
  author: Stefan Sebekow
  defaultTheme: dark
  ShowShareButtons: false
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  images: [""]
  


  homeInfoParams:
    Title: "Hi! Mein Name ist Stefan. Willkommen auf meinem Blog."
    Content: >
     Ich bin passionierter Systemadministrator und Teamleiter und interessiere mich für alle Themen rund um Administration
     und Netzwerk. In diesem Blog dokumentiere ich meine alten und zukünftigen Projekte, während ich besser Programmieren lerne, meinen Blog mit Hugo aufbaue und meine Powershell- und Bash-Kenntnisse verbessere. Momentan bin ich im Bereich der klinischen Forschung in einer der größten Kohortenstudien weltweit tätig
     <br /> Kontakt: **mail {äät} stefansblog.org**
     <br/><br/> 
     <div class="container">
     <img class="special-img-class" src="/images/Portrait3.png" width="212" height="280" />
     </div>

  socialIcons:
    - name: github
      title: View Source on Github
      url: "https://github.com/stefansebekow"
    - name: LinkedIn
      title: LinkedIn
      url: "https://www.linkedin.com/in/stefan-sebekow/"  


markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

search results:
